### ISSUE TITLE
Getting Error in outbound connection setup

### ISSUE THREAD

**Issue by mohit3089** [SAP-samples/logistics-business-network-integration#2]
Hi team,

We are getting the below-given message in the outbound connection test service. please let me know how to fix the outbound connection.

![Screenshot 2021-03-03 at 9 50 15 PM](https://user-images.githubusercontent.com/19772360/109837024-c34e5380-7c6a-11eb-85f1-b94cc5efbfab.png)

**Comment by RavishShettySAP** [comment]
Please provide the LBNID for your tenant. A dummy relationship to one of the internal test tenant has to be established. You may request it by creating an incident to SCM-LBN-INT

**Comment by mohit3089** [comment]
Here is the ID (2497837)

**Comment by RavishShettySAP** [comment]
Seems like the LBNID is incorrect. It is a 11 digit no. You can view it in the Manage Business Profile App. Also what's the name of that you have maintained in the Business Profile

**Comment by mohit3089** [comment]
LSorry, here is the correct id LBN ID:10010001467

**Comment by RavishShettySAP** [comment]
An invite is already sent to your tenant. You need to accept the invite in manage invitations app

**Comment by mohit3089** [comment]
Hi Ravish, 

Yes, we got the invitation and accepted it. Can you tell me how to check what request is sent to our outbound endpoint? because I did not find any request in my logs from SAP LBN.

**Comment by RavishShettySAP** [comment]
org.apache.camel.component.ahc.AhcOperationFailedException: HTTP operation failed invoking https://api-staging.stagingfareyeconnect.com/connector/api/Connector/v1/sapLbnTest/test-service with statusCode: 404

**Comment by RavishShettySAP** [comment]
We 

> org.apache.camel.component.ahc.AhcOperationFailedException: HTTP operation failed invoking https://api-staging.stagingfareyeconnect.com/connector/api/Connector/v1/sapLbnTest/test-service with statusCode: 404

We get this error

**Comment by mohit3089** [comment]
Thanks for your support, we have received the request successfully in the outbound connection.
