### ISSUE TITLE
LBN inbound endpoint

### ISSUE THREAD

**Issue by hbensalem** [SAP-samples/logistics-business-network-integration#3]
What's the correct endpoint to test posting events and milestones. I tried https://l20398-iflmap.hcisbp.eu1.hana.ondemand.com/http/v1h/tracking/events  but it did not work for me

**Comment by RavishShettySAP** [comment]
https://l20398-iflmap.hcisbp.eu1.hana.ondemand.com/http/http/v1/tracking/events.   This is the right one.

**Comment by benoy1186** [comment]
any step by step document for integrating TM with CPI to LBN

**Comment by RavishShettySAP** [comment]
Refer blog https://blogs.sap.com/2020/10/12/how-to-setup-direct-connection-from-your-on-prem-to-sap-logistics-business-network-freight-collaboration-option/#step3

**Comment by benoy1186** [comment]
Hi Ravish,
 I have gone through your blog ,appreciate the wonderful and well explained blog .it explains Option 2 , If we could have the same for Integration through CPI as we have 3 standard packages in CPI for LBN ,it would be great.

**Comment by benoy1186** [comment]
Hi Ravish,

 I have gone through your blog ,appreciate the wonderful and well explained
blog .it explains Option 2 ,
If we could have the same for Integration through CPI as we have 3 standard
packages in CPI for LBN ,it would be great.
